### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nickels** [tomdebree/VEcan#1]
Hello @Tom-evnut,

Do I understand correctly that you can use this repo to transmit vecan data (for example SoC from Lynx Shunt) to can protocol to use this data in a 3rd party BMS (e.g. Batrium)?

If yes, how would I install this on my Cerbo GX?

Thank you!

**Comment by Tom-evnut** [comment]
No this is to allow someone to write code for a microcontroller to communicate with standard Victron GX equipment.
